name: motor_network
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - tqdm
  - jupyter
  - numba
  - pip:
      - brainpy==2.7.6
      - jax==0.6.2
      - jaxlib==0.6.2
